import type { Metadata } from 'next';
import styles from '../../components/Header/Login/styles.module.sass';
const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={styles.body}>{children}</body>
    </html>
  );
}
